export const MATRIX_CONNECTION = {
	CONNECTED: "CONNECTED",
	DISCONNECTED: "DISCONNECTED",
	ADDRESS_NOT_FOUND: "ADDRESS_NOT_FOUND"
};

export const UPDATE_MATRIX_CONNECTION_STATE = "UPDATE_MATRIX_CONNECTION_STATE";