
/**
 * Matrix
 */
export const NEW_VIDEO_CONNECTION = "NEW_VIDEO_CONNECTION";
export const NEW_KWM_CONNECTION = "NEW_KWM_CONNECTION";
export const SET_VIDEO_CONNECTION = "SET_VIDEO_CONNECTION";
export const SET_KWM_CONNECTION = "SET_KWM_CONNECTION";
export const VIDEO_CONNECTION_TURN_OFF = "VIDEO_CONNECTION_TURN_OFF";
export const KWM_CONNECTION_TURN_OFF = "KWM_CONNECTION_TURN_OFF";
export const TURN_OFF_VIDEO_CONNECTION = "TURN_OFF_VIDEO_CONNECTION";
export const TURN_OFF_KWM_CONNECTION = "TURN_OFF_KWM_CONNECTION";